//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EATMVC.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EducationAndTrainingEntities : DbContext
    {
        public EducationAndTrainingEntities()
            : base("name=EducationAndTrainingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<GP_Login> GP_Login { get; set; }
        public DbSet<GP_LoginRoleInfo> GP_LoginRoleInfo { get; set; }
        public DbSet<RoleInfo> RoleInfo { get; set; }
    }
}
