//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EATMVC.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GP_Login
    {
        public string name { get; set; }
        public string id { get; set; }
        public string password { get; set; }
        public string real_name { get; set; }
        public string training_base_code { get; set; }
        public string training_base_name { get; set; }
        public string type { get; set; }
        public string LoginState { get; set; }
        public string RegisterDate { get; set; }
        public string professional_base_code { get; set; }
        public string professional_base_name { get; set; }
        public string dept_code { get; set; }
        public string dept_name { get; set; }
    }
}
